@Vini.ModularMonolith.Example.Web_HostAddress = https://localhost:7018

GET {{Vini.ModularMonolith.Example.Web_HostAddress}}/books/
Accept: application/json

###

@BookId = e4fa19bf-6981-4e50-a542-7c9b26e9ec31

GET {{Vini.ModularMonolith.Example.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

###

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "bda13026-666e-425a-8cf2-5ceabfc8aea6",
  "title": "Wheel Of Time: The Eye of the World",
  "author": "Robert Jordan",
  "price": 13.15
}

###

DELETE {{Vini.ModularMonolith.Example.Web_HostAddress}}/books/bda13026-666e-425a-8cf2-5ceabfc8aea6
Accept: application/json

###

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/books/bda13026-666e-425a-8cf2-5ceabfc8aea6/pricehistory
Accept: application/json
Content-Type: application/json

{
  "NewPrice": 10.15
}

###

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "vbsanttos@gmail.com",
  "password": "Pass@word1"
}

###

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "vbsanttos@gmail.com",
  "password": "Pass@word1"
}

###

@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzM2OTA0MTUsIkVtYWlsQWRkcmVzcyI6InZic2FudHRvc0BnbWFpbC5jb20iLCJleHAiOjE3MzM2OTQwMTUsIm5iZiI6MTczMzY5MDQxNX0.cZ44kzXLPQTy8qp8U0luuRYXFdXV5ipzMPoCE4Tzb9g

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json 
{
  "bookId": "e4fa19bf-6981-4e50-a542-7c9b26e9ec31",
  "quantity": 1
}

###

GET {{Vini.ModularMonolith.Example.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{Vini.ModularMonolith.Example.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# Checkout Cart
POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/cart/checkout
Accept: application/json 
Authorization: Bearer {{token}}
Content-Type: application/json 
{
  "billingAddressId": "53d9bac5-2517-4ca3-b8d3-509736b10d4d",
  "shippingAddressId": "53d9bac5-2517-4ca3-b8d3-509736b10d4d"
}

###

# List Addresses
GET {{Vini.ModularMonolith.Example.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add Address To User
POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/users/addresses
Accept: application/json 
Authorization: Bearer {{token}}
Content-Type: application/json 
{
  "street1": "Rua Floriano Peixoto",
  "street2": "Apto 201",
  "city": "Santa Maria",
  "state": "RS",
  "postalCode": "97010-100",
  "country": "Brazil"
}

###

# FLUSH CACHE

POST {{Vini.ModularMonolith.Example.Web_HostAddress}}/flushcache
Accept: application/json
Content-Type: application/json
{
}

###
